import os
import yaml
import hto
import scipy
import numpy as np
import pandas as pd
import anndata as ad
import datetime
import yaml
import matplotlib.pyplot as plt
import matplotlib.ticker as mticks
import seaborn as sns
import warnings
warnings.filterwarnings("ignore", category=FutureWarning)


class ReportData:
    """
    Class to process data for report.
    """
    def __init__(self, sample_name, path_h5ad, path_report, path_reads):
        # inputs
        self.sample_name = sample_name
        self.path_h5ad = path_h5ad
        self.path_report = path_report
        self.path_reads = path_reads

        # read data
        data = self.read_data()
        self.adata = data["adata"]
        self.run_report = data["run_report"]
        self.reads = data["reads"]

        # parameters
        self.cmap = self.get_cmap()
        self.n_rows = 5

        # map fields
        self.mapped_fields = {
            "text_date_created": {
                "generator": self.generate_text_date_created,
                "type": "text"
            },
            "table_metrics": {
                "generator": self.generate_table_metrics,
                "type": "table"
            },
            "table_warnings": {
                "generator": self.generate_table_warnings,
                "type": "table"
            },
            "plot_celltypes": {
                "generator": self.generate_plot_celltypes,
                "type": "plot"
            },
            "plot_distributions": {
                "generator": self.generate_plot_distributions,
                "type": "plot"
            },
            "plot_denoising": {
                "generator": self.generate_plot_denoising,
                "type": "plot"
            },
            "plot_expression_signal": {
                "generator": self.generate_plot_expression_signal,
                "type": "plot"
            },
            "plot_expression_singlets": {
                "generator": self.generate_plot_expression_singlets,
                "type": "plot"
            },
            "text_runreport": {
                "generator": self.generate_text_runreport,
                "type": "text"
            },
            "table_umis_raw": {
                "generator": self.generate_table_umis_raw,
                "type": "table"
            },
            "table_umis_normalised": {
                "generator": self.generate_table_umis_normalised,
                "type": "table"
            },
            "table_umis_denoised": {
                "generator": self.generate_table_umis_denoised,
                "type": "table"
            },
            "table_reads_raw": {
                "generator": self.generate_table_reads_raw,
                "type": "table"
            },
        }

    def read_data(self):
        """
        Read in data for hashtag report:
        - adata: containing HTO counts
        - run_report: generated by CITE-seq-Count
        - reads: containing raw HTO reads
        """

        def remove_sequence(x):
            """
            Columns are stored as: A0252-AGTCAGATA
            Remove sequence for better readability
            """
            return [":".join(i.split("-")[0] for i in item.split(":")) for item in x]

        # read anndata
        adata = ad.read_h5ad(self.path_h5ad)
        adata.var_names = remove_sequence(adata.var_names)
        adata.obs["hash_id"] = remove_sequence(adata.obs["hash_id"])
        adata.obs["doublet_info"] = remove_sequence(adata.obs["doublet_info"])
        adata.uns["dnd"]["demux"]["thresholds"] = {k.split("-")[0]: v for k, v in adata.uns["dnd"]["demux"]["thresholds"].items()}

        # read report
        with open(self.path_report, 'r') as f:
            text = f.read().replace("\t", "  ")
            run_report = yaml.safe_load(text)

        # read raw reads
        barcodes = pd.read_csv(os.path.join(self.path_reads, "barcodes.tsv.gz"), header=None)[0]
        features = pd.read_csv(os.path.join(self.path_reads, "features.tsv.gz"), header=None)[0]
        features = [f.split("-")[0] for f in features]
        matrix = scipy.io.mmread(os.path.join(self.path_reads, "matrix.mtx.gz")).T.tocsr()
        reads = pd.DataFrame(matrix.toarray(), index=barcodes, columns=features)

        # out
        out = {
            "adata": adata,
            "run_report": run_report,
            "reads": reads
        }
        return out

    def get_cmap(self):
        hash_ids = self.adata.var_names.tolist()
        cmap = dict(zip(hash_ids, sns.color_palette("tab20")))
        cmap = {**cmap, "doublet": "grey", "negative": "lightgrey"}
        return cmap

    def generate_text_date_created(self):
        return datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    @staticmethod
    def format_unit(v, unit):
        """Format value with unit for display."""
        if unit == "%":
            return f"{v:.1f}{unit}"
        elif unit == "K":
            return f"{v/1e3:.1f}{unit}"
        elif unit == "M":
            return f"{v/1e6:.1f}{unit}"
        elif isinstance(v, float):
            return f"{v:.1f}{unit}"
        else:
            return f"{v}{unit}"

    def generate_table_metrics(self):
        """
        Two Stages to generate metrics for hashtag report:
        1. Compute raw metrics from data
        2. Derive summary metrics with interpretations
        """

        # --- Stage 1: Compute raw metrics --- #

        # mapping rate
        mapping_rate = self.run_report["Percentage mapped"]

        # outlier HTO
        hto_counts = self.adata.obs["hash_id"].value_counts()
        hto_props = hto_counts / hto_counts.sum()
        hto_props_singlets = hto_props[~hto_props.index.isin(["doublet", "negative"])]
        hto_prop_lowest_prop = hto_props_singlets.min()
        hto_prop_lowest_label = hto_props_singlets.idxmin()
        hto_props_dict = hto_props.to_dict()
        doublet = hto_props.get("doublet", 0)
        negative = hto_props.get("negative", 0)
        doublet_prop = doublet / hto_counts.sum()
        negative_prop = negative / hto_counts.sum()

        hash_ids = self.adata.var_names.tolist()
        n_htos = len(hash_ids)
        n_cells = self.adata.shape[0]

        # sequencing depth
        sum_umi = self.adata.X.sum()
        sum_reads = self.reads.sum().sum()
        reads_total = self.run_report["Reads processed"]
        reads_per_umi = sum_reads / sum_umi
        reads_in_cells = sum_reads / reads_total
        unmapped_reads_q99 = np.quantile(self.reads.loc[self.adata.obs_names, "unmapped"], .95)

        # low signal
        unstained_cells = sum(self.reads.loc[self.adata.obs_names].sum(1) < 5)
        unstained_cells_prop = unstained_cells / n_cells

        # --- Stage 2: Derive summary metrics with interpretations --- #

        # general metrics
        metrics_list = [
            {
                "Metric": "Number of Cells",
                "Value": n_cells,
                "Unit": "K",
                "Source & Implication": "Total number of cells detected. Low numbers may indicate poor capture efficiency.",
                "Highlight": n_cells < 500
            },
            {
                "Metric": "Number of HTOs",
                "Value": n_htos,
                "Unit": "",
                "Source & Implication": "Total number of hashtags used. If only one, demultiplex manually.",
                "Highlight": n_htos < 2,
            },
            {
                "Metric": "Total Reads",
                "Value": reads_total,
                "Unit": "M",
                "Source & Implication": "Total number of reads sequenced. Low numbers may indicate shallow sequencing.",
                "Highlight": reads_total < 2e6
            },
            {
                "Metric": "Number of Reads in Cells",
                "Value": sum_reads,
                "Unit": "M",
                "Source & Implication": "Number of valid reads found in cells. Low numbers may indicate shallow sequencing, high contamination or low mapping quality.",
                "Highlight": sum_reads < 1e6
            },
            {
                "Metric": "Number of UMIs",
                "Value": sum_umi,
                "Unit": "M",
                "Source & Implication": "Total number of unique molecular identifiers. Low numbers may indicate poor library complexity.",
                "Highlight": sum_umi < 5e5
            },
            {
                "Metric": "Reads per UMI",
                "Value": reads_per_umi,
                "Unit": "",
                "Source & Implication": "Sequencing saturation measure. Low values may indicate shallow sequencing.",
                "Highlight": reads_per_umi < 1.2
            },
            {
                "Metric": "Reads in Cells",
                "Value": reads_in_cells,
                "Unit": "%",
                "Source & Implication": "Percentage of reads from cells. Low values may indicate poor capture efficiency or high contamination.",
                "Highlight": reads_in_cells < 1.2
            },
            {
                "Metric": "Mapping rate",
                "Value": mapping_rate,
                "Unit": "%",
                "Source & Implication": "Fraction of reads mapped to reference. Low may indicate contamination, wrong reference (probe barcodes), or poor library prep.",
                "Highlight": mapping_rate < 20
            },
            {
                "Metric": "Unmapped Reads (Q99)",
                "Value": unmapped_reads_q99,
                "Unit": "K",
                "Source & Implication": "95-Quantile of reads not matching any barcode. High values suggest missing barcodes or contamination",
                "Highlight": unmapped_reads_q99 > 1e5
            },
            {
                "Metric": f"HTO {hto_prop_lowest_label} representation",
                "Value": hto_prop_lowest_prop * 100,
                "Unit": "%",
                "Source & Implication": "Fraction of singlets for this HTO. Low values suggest unbalanced hashing or sample dropout.",
                "Highlight": hto_prop_lowest_prop < (1 - doublet_prop - negative_prop) / (3 * n_htos)
            },
            {
                "Metric": "Doublets",
                "Value": f"{doublet:.1f} ({doublet_prop:.1%})",
                "Unit": "",
                "Source & Implication": "Cells classified as doublets. High levels reduce assignment accuracy.",
                "Highlight": doublet_prop > 0.30
            },
            {
                "Metric": "Negative Proportion",
                "Value": f"{negative:.1f} ({negative_prop:.1%})",
                "Unit": "",
                "Source & Implication": "Cells with no clear HTO signal. High values may indicate inefficient hashing or failed capture.",
                "Highlight": negative_prop > 0.30
            },
            {
                "Metric": "Unstained Cells",
                "Value": f"{unstained_cells / 1000:.1f}K ({unstained_cells_prop:.1%})",
                "Unit": "",
                "Source & Implication": "Unstained cells express <5 antibody tags. High counts suggest dropout between GEX and HTO..",
                "Highlight": unstained_cells_prop > .05,
            }
        ]

        # compile
        df_metrics = pd.DataFrame(metrics_list)
        df_metrics.loc[:, 'Value'] = df_metrics.apply(
            lambda row: self.format_unit(row['Value'], row['Unit']), axis=1
        )
        return df_metrics

    def generate_table_warnings(self):
        """Same as generate_table_metrics but only return warnings."""
        # --- Stage 1: Compute raw metrics --- #

        hash_ids = self.adata.var_names.tolist()
        signal = {}
        background = {}
        log_ratios = {}
        for hash_id in hash_ids:
            sub = self.adata.obs["hash_id"] == hash_id
            signal[hash_id] = np.mean(self.adata[sub, hash_id].X)
            background[hash_id] = np.mean(self.adata[~sub, hash_id].X)
            log_ratios[hash_id] = np.log2(signal[hash_id] / background[hash_id]) if background[hash_id] > 0 else np.nan

        # --- Stage 2: Derive summary metrics with interpretations --- #

        # hashtag specific
        metrics_list = []
        for hash_id, sig in signal.items():
            metrics_list.append({
                "Metric": f"HTO {hash_id} signal",
                "Value": sig,
                "Unit": "",
                "Source & Implication": "Average UMI count per cell. Low signal suggests weak staining or barcode dropout.",
                "Highlight": sig < 20
            })

        # Log2 ratios per HTO
        for hash_id, lr in log_ratios.items():
            metrics_list.append({
                "Metric": f"HTO {hash_id} log2 ratio",
                "Value": 0 if np.isnan(lr) else lr,
                "Unit": "",
                "Source & Implication": "Signal vs background separation. Low values reduce demultiplexing confidence.",
                "Highlight": np.isnan(lr) or lr < 1.5
            })

        # compile
        df_metrics = pd.DataFrame(metrics_list)
        df_metrics = df_metrics[df_metrics["Highlight"]]
        df_metrics.loc[:, 'Value'] = df_metrics.apply(
            lambda row: self.format_unit(row['Value'], row['Unit']), axis=1
        )
        return df_metrics

    def generate_plot_celltypes(self):
        # data
        adata = self.adata
        counts = adata.obs["hash_id"].value_counts()

        # figure
        fig, ax = plt.subplots(1, 1, figsize=(10, 5))

        # barplot
        ax = sns.barplot(
            x=counts.index,
            y=counts.values,
            hue=counts.index,
            ax=ax,
            palette=self.cmap
        )
        ax.set_ylabel("Cell Count")
        ax.set_title("HTO Cell Counts")

        # annotate
        for i, p in enumerate(ax.patches):
            count = counts.iloc[i]
            ax.text(
                x=i,
                y=count,
                s=f"{count/1e3:.1f}K\n({count / sum(counts):.1%})",
                ha="center",
                va="center",
            )

        ylim = ax.get_ylim()
        ax.set_ylim(ylim[0], ylim[1] * 1.1)
        ax.yaxis.grid(False)
        ax.yaxis.set_major_formatter(mticks.FuncFormatter(lambda x, pos: f"{x/1e3:.0f}K"))
        ax.set_xlabel("")
        return fig

    def generate_plot_distributions(self):
        axs = hto.pl.distribution_stages(self.adata, cmap=self.cmap)
        return axs[0].get_figure()

    def generate_plot_denoising(self):
        _, axs = hto.pl.technical_noise(adata=self.adata, var=0)
        return axs[0][0].get_figure()

    def generate_plot_expression_signal(self):
        # get data
        df = self.adata.to_df().join(self.adata.obs[["hash_id"]])

        # wide to long
        df_long = df.melt(id_vars="hash_id", value_name="expression", var_name="hashtag")
        df_long.loc[:, "hash_id_is_hashtag"] = df_long["hash_id"] == df_long["hashtag"]
        df_long.loc[:, "expression_log"] = np.log1p(df_long["expression"])
        df_long_singlets = df_long[~df_long["hash_id"].isin(["doublet", "negative"])]

        # plot
        fig, ax = plt.subplots(figsize=(12, 6))
        ax = sns.boxplot(
            df_long_singlets,
            x="hashtag",
            y="expression_log",
            hue="hash_id_is_hashtag",
            showfliers=False,
            orient="v",
            width=.7,
            ax=ax,
        )

        # change legend title
        ax.legend(title="Assigned to this Hashtag")
        ax.set_title("Log HTO Expression between assigned and not assigned cells.")
        ax.set_ylabel("Log HTO Expression")
        ax.set_xlabel("Hashtag")
        return fig

    def generate_plot_expression_singlets(self):
        df = self.adata.to_df().sum(1).to_frame("expression").join(self.adata.obs["hash_id"])
        df.loc[:, "label"] = df["hash_id"].apply(lambda x: x if x in ["doublet", "negative"] else "singlet")
        df.loc[:, "expression_log"] = np.log1p(df["expression"])

        fig, ax = plt.subplots(figsize=(12, 6))
        ax = sns.boxplot(
            df,
            y="expression_log",
            hue="label",
            showfliers=False,
            orient="v",
            width=.7,
            ax=ax,
        )

        # change legend title
        ax.set_title("Log HTO Expression between negative, singlets and doublets.")
        ax.set_ylabel("Log HTO Expression")
        ax.set_xlabel("Category")
        return fig

    def generate_text_runreport(self):
        # yaml to string with 4 space indentation and newlines
        return yaml.dump(self.run_report, indent=4, default_flow_style=False)

    def generate_table_umis_raw(self):
        """Return adata.to_df().head(n) as html"""
        df = self.adata.to_df().head(self.n_rows)
        return df

    def generate_table_umis_normalised(self):
        df = self.adata.to_df("normalised").head(self.n_rows)
        return df

    def generate_table_umis_denoised(self):
        df = self.adata.to_df("denoised").head(self.n_rows)
        return df

    def generate_table_reads_raw(self):
        df = self.reads.loc[self.adata.obs_names].head(self.n_rows)
        return df
